namespace Mercury.Generators.ModuleDescriptions;

internal static class ModuleDescriptionTemplates {
    public const string ModuleDescriptionAttribute =
        """
        // <auto-generated/>

        using System;
        using Mercury.Editor.Models.Modules;

        namespace Mercury.Editor.Generators.Modules;

        /// <summary>
        /// Marks that a class is an <see cref="ModuleDescription"/>.
        /// </summary>
        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public class ModuleDescriptionAttribute : Attribute { }
        """;
    
    public const string PropertyNameAttribute =
        """
        // <auto-generated/>

        using System;
        using Mercury.Editor.Models.Modules;

        namespace Mercury.Editor.Generators.Modules;

        /// <summary>
        /// Marks which localization property should be used to name this property.
        /// </summary>
        [AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
        public class PropertyNameAttribute : Attribute {
            public PropertyNameAttribute(string localizationKeyName) {
            }
        }
        """;

    public const string ModuleDescriptionClassFormat =
        """
        // <auto-generated/>
        
        using System;
        using System.Reflection;
        using System.Collections.Generic;
        using System.Linq;
        using Mercury.Editor.Models.Modules.Properties;
        
        namespace {0};
        
        public partial class {1} {{
        {2}
        }}
        """;

    public const string GetSpecificPropertiesFormat =
        """
            protected override List<ModuleProperty> GetSpecificProperties() {{
                Type t = GetType();
                PropertyInfo[] props = t.GetProperties();
        {0}
                return [
        {1}
                ];
            }}
        """;

    public const string GetPropertyInfoFormat =
        """
                PropertyInfo {0} = props.First(x => x.Name == "{1}");
        """;

    public const string CreatePropertyFormat =
        """
                    new {0}(Localization.ModuleDescriptions.{1}, {2}, this),
        """;

    public const string BaseModuleDescriptionFormat =
        """
        // <auto-generated/>
        
        using System;
        using System.Reflection;
        using System.Collections.Generic;
        
        namespace Mercury.Editor.Models.Modules;
        
        public partial class ModuleDescription {{
            /// <summary>
            /// Returns a list of types that registered themselves at initialization as possible <see cref="ModuleDescription"/>
            /// to be used in the application.
            /// </summary>
            public static List<Type> GetAvailableModules() {{
                return [
        {0}
                ];
            }}
        }}
        """;

    public const string BaseModuleDescriptionTypeofFormat =
        """
                    typeof({0}),
        """;
}