namespace Mercury.Generators.Instruction;

internal static class InstructionTemplates {
    
    internal static class Attributes {
        public const string InstructionAttribute =
            """
            // <auto-generated/>

            using System;

            namespace Mercury.Engine.Generators.Instruction;

            /// <summary>
            /// Marks that a class is an instruction and should be analyzed by Mercury and have code generated for it.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
            public class InstructionAttribute : Attribute { }
            """;

        public const string SignedAttribute =
            """
            // <auto-generated/>
            
            using System;
            
            namespace Mercury.Engine.Generators.Instruction;
            
            /// <summary>
            /// Marks that a class is an instruction and should be analyzed by Mercury and have code generated for it.
            /// </summary>
            [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
            public class SignedAttribute : Attribute { }
            """;

        public const string FieldAttribute =
            """
            // <auto-generated/>

            using System;

            namespace Mercury.Engine.Generators.Instruction;

            /// <summary>
            /// Marks that a field or property must be populated with data from the binary instruction on decoding.
            /// </summary>
            [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
            public class FieldAttribute : Attribute {
                /// <summary>
                /// Creates the attribute that marks the field.
                /// </summary>
                /// <param name="bitStart">The inclusive index of the first bit</param>
                /// <param name="bitEnd">The inclusive index of the last bit</param>
                public FieldAttribute(int bitStart, int bitEnd) { }
            }
            """;

        public const string AssemblyFormatAttribute =
            """
            // <auto-generated/>

            using System;

            namespace Mercury.Engine.Generators.Instruction;

            /// <summary>
            /// Specifies the assembly string format for the instruction.
            /// Format placeholders can reference properties/fields. Special specifiers like :reg (general register),
            /// :fpreg (float register), and :fmt (FPU format) will generate standard translation calls.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            public class AssemblyFormatAttribute : Attribute {
                public string Format { get; }
                public AssemblyFormatAttribute(string format) {
                    Format = format;
                }
            }
            """;

        public const string AssemblyFormatterAttribute =
            """
            // <auto-generated/>

            using System;

            namespace Mercury.Engine.Generators.Instruction;

            /// <summary>
            /// Decorates a static method that formats a field value into its assembly string representation.
            /// </summary>
            [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            public class AssemblyFormatterAttribute : Attribute {
                public string Specifier { get; }
                public AssemblyFormatterAttribute(string specifier) {
                    Specifier = specifier;
                }
            }
            """;

        public const string AssemblyParserAttribute =
            """
            // <auto-generated/>

            using System;

            namespace Mercury.Engine.Generators.Instruction;

            /// <summary>
            /// Decorates a static method that parses an assembly string representation back into a field value.
            /// </summary>
            [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            public class AssemblyParserAttribute : Attribute {
                public string Specifier { get; }
                public AssemblyParserAttribute(string specifier) {
                    Specifier = specifier;
                }
            }
            """;

        public const string FormatExactAttributeText =
            """
            // <auto-generated />
            using System;

            namespace Mercury.Engine.Generators.Instruction;

            /// <summary>
            /// Specifies a constraint on the bit values of an instruction.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
            public class FormatExactAttribute : Attribute {

                /// <summary>
                /// Specifies that a bit span of the instruction must match any of the provided values.
                /// </summary>
                public FormatExactAttribute(int bitStart, int bitEnd, int[] values) {
                    
                }
                
                /// <summary>
                /// Specifies that a bit span of the instruction must match the provided value.
                /// </summary>
                public FormatExactAttribute(int bitStart, int bitEnd, int value) {
                    
                }
            }
            """;

        public const string FormatDifferentAttribute =
            """
            // <auto-generated />
            using System;

            namespace Mercury.Engine.Generators.Instruction;

            /// <summary>
            /// Specifies a constraint on the bit values of an instruction. Demands
            /// that a span of the instruction must not match a value. 
            /// </summary>
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
            public class FormatDifferentAttribute : Attribute {

                /// <summary>
                /// Specifies that a bit span of the instruction must not match any of the provided values.
                /// </summary>
                public FormatDifferentAttribute(int bitStart, int bitEnd, int[] values) {
                    
                }
                
                /// <summary>
                /// Specifies that a bit span of the instruction must not match the provided value.
                /// </summary>
                public FormatDifferentAttribute(int bitStart, int bitEnd, int value) {
                    
                }
            }
            """;
    }

    public const string PartialInstruction =
        """
        // <auto-generated/>

        namespace {0};

        public partial class {1} {{
            public void FromInt(uint value) {{
        {2}
            }}
            
            public uint ConvertToInt() {{
        {3} 
            }}
        {4}
        }}
        """;

    public const string PartialInstructionFieldExtract =
        """
                {0} = ({1})((value >> {2}) & {3});
        """;
    
    public const string PartialInstructionSignedFieldExtract =
        """
                {0} = ({1})global::Mercury.Engine.Common.Extensions.SignExtend<{1}>(({1})((value >> {2}) & {3}), {4});
        """;

    public const string DisassemblerFormat =
        """
        // <auto-generated />
        #nullable enable
        using System;
        using System.Runtime.CompilerServices;

        namespace {0};

        /// <summary>
        /// Simple wrapper class for the <see cref="Disassemble"/> method.
        /// </summary>
        /// <remarks>{1} instructions registered.</remarks>
        public class Disassembler : Mercury.Engine.Common.IInstructionDisassembler {{
            
            public global::Mercury.Engine.Common.IInstruction? Decode(uint instruction, Mercury.Engine.Common.IInstructionPool pool) {{
                if(pool is not InstructionPool poolSpecific) {{
                    throw new Exception($"Wrong instruction pool type. Should be {0}.InstructionPool, but was {{pool.GetType().FullName}} instead.");
                }}
                return Disassemble(instruction, poolSpecific);
            }}

            private static global::Mercury.Engine.Common.IInstruction? GetType(uint instruction, InstructionPool pool) {{
        {2}
                return null;
            }}
            
            public static global::Mercury.Engine.Common.IInstruction? Disassemble(uint instruction, InstructionPool pool) {{
                global::Mercury.Engine.Common.IInstruction? type = GetType(instruction, pool);
                if (type is null) {{
                    return null;
                }}
                type.FromInt(instruction);
                return type;
            }}
        }}
        """;

    public const string PoolFormat =
        """
        // <auto-generated />
        #nullable enable
        using System;

        namespace {0};

        /// <summary>
        /// A class that has all available instructions in its fields. Used to avoid allocations
        /// of the same instructions. 
        /// </summary>
        public class InstructionPool : Mercury.Engine.Common.IInstructionPool {{
        {1}
        }}
        """;
}