using System;
using System.Collections.Generic;
using System.IO;
using ELFSharp.ELF;

namespace SAAE.Editor.Models.Compilation;

/// <summary>
/// A structure with information about the result
/// of a compilation process.
/// </summary>
/// <remarks>The <see cref="Dispose"/> method does not
/// clean up <see cref="OutputStream"/> and <see cref="OutputElf"/>
/// if they were generated</remarks>
public readonly struct CompilationResult : IDisposable
{
    /// <summary>
    /// A unique identifier for this compilation. If all the
    /// input files are the same, the identifier will be the same.
    /// </summary>
    public Guid Id { get; init; }
    
    /// <summary>
    /// Whether the compilation was successful or not.
    /// </summary>
    public bool IsSuccess { get; init; }

    /// <summary>
    /// The type of error that ocurred if <see cref="IsSuccess"/> is false.
    /// </summary>
    public CompilationError Error { get; init; }
    
    /// <summary>
    /// A list with all the diagnostics generated by the compilation
    /// </summary>
    public List<Diagnostic>? Diagnostics { get; init; }
    
    /// <summary>
    /// A stream to the binary output of the compilation process.
    /// </summary>
    public Stream? OutputStream { get; init; }
    
    /// <summary>
    /// The output processed as an ELF file.
    /// </summary>
    public IELF? OutputElf { get; init; }

    public void Dispose() {
        // dispose outputstream e elf?
    }
}